language: php

php:
  - 7.2
  - 7.1

install:
  - composer install

jobs:
  include:
    - stage: deploy
      install:
        - yarn install
      script: yarn docs:build
      deploy:
        provider: pages
        committer-from-gh: true
        skip-cleanup: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        local-dir: docs/.vuepress/dist
        target-branch: master
        repo: morphose/morphose.github.io
        on:
          branch: master
