language: php

php:
  - '7.2'

install:
  - composer install

jobs:
  include:
    - stage: deploy
      install:
        - yarn install
      script: yarn docs:build
      deploy:
        provider: pages
        committer-from-gh: true
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs/.vuepress/dist
        on:
          branch: master
