jobs:
  include:
    - branches:
        only:
          - master
      install:
        - composer install
      name: phpunit
      php: '7.2'
      stage: test
    - branches:
        only:
          - master
      deploy:
        provider: pages
        committer-from-gh: true
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: docs/.vuepress/dist
      install:
          - yarn install
      name: docs
      script: yarn docs:build
      stage: deploy
